# 01. 원본 데이터 개요

`data/raw`의 Olist CSV 9개를 읽어 테이블별로 아래 항목을 확인한다.

- 행 수, 열 수
- 컬럼명과 데이터 타입
- 컬럼별 결측치 개수와 비율
- 중복 행 개수
- 상위 3행 미리보기

원본 파일은 읽기만 하고 수정하지 않는다.

In [1]:
from pathlib import Path

import pandas as pd
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)


def find_project_root(start: Path) -> Path:
    """data/raw 폴더가 있는 프로젝트 루트를 찾는다."""
    for path in [start, *start.parents]:
        if (path / "data" / "raw").is_dir():
            return path
    raise FileNotFoundError("프로젝트 루트(data/raw)를 찾을 수 없습니다.")


PROJECT_ROOT = find_project_root(Path.cwd())
RAW_DIR = PROJECT_ROOT / "data" / "raw"
csv_files = sorted(RAW_DIR.glob("*.csv"))
print(f"CSV 파일 {len(csv_files)}개")
for f in csv_files:
    print(f" - {f.name}")

CSV 파일 9개
 - olist_customers_dataset.csv
 - olist_geolocation_dataset.csv
 - olist_order_items_dataset.csv
 - olist_order_payments_dataset.csv
 - olist_order_reviews_dataset.csv
 - olist_orders_dataset.csv
 - olist_products_dataset.csv
 - olist_sellers_dataset.csv
 - product_category_name_translation.csv

## CSV 읽기

기본은 `encoding="utf-8"`로 읽고, 첫 번째 컬럼명 앞에 BOM(`\ufeff`) 같은 이상한 문자가 붙어 있으면 그 파일만 `encoding="utf-8-sig"`로 다시 읽는다.

In [2]:
def has_strange_prefix(column_name: str) -> bool:
    """컬럼명 앞에 BOM 등 이상한 문자가 붙어 있는지 확인한다."""
    first_char = str(column_name)[:1]
    return first_char == "\ufeff" or not (first_char.isalnum() or first_char == "_")


def read_csv_safely(path: Path) -> tuple[pd.DataFrame, str]:
    """utf-8로 읽고, 첫 컬럼명이 이상하면 utf-8-sig로 다시 읽는다."""
    df = pd.read_csv(path, encoding="utf-8")
    if has_strange_prefix(df.columns[0]):
        print(f"[{path.name}] 첫 컬럼명 {df.columns[0]!r} → utf-8-sig로 다시 읽음")
        return pd.read_csv(path, encoding="utf-8-sig"), "utf-8-sig"
    return df, "utf-8"


tables: dict[str, pd.DataFrame] = {}
encodings: dict[str, str] = {}
for path in csv_files:
    name = path.stem
    tables[name], encodings[name] = read_csv_safely(path)

print(f"\n{len(tables)}개 테이블 로드 완료")

9개 테이블 로드 완료

## 테이블별 상세 확인

In [3]:
def column_profile(df: pd.DataFrame) -> pd.DataFrame:
    """컬럼별 데이터 타입, 결측치 개수와 비율을 표로 만든다."""
    null_count = df.isna().sum()
    return pd.DataFrame({
        "dtype": df.dtypes.astype(str),
        "null_count": null_count,
        "null_ratio(%)": (null_count / len(df) * 100).round(2),
    })


def describe_table(name: str, df: pd.DataFrame) -> None:
    """테이블 하나의 기본 정보를 출력한다."""
    print("=" * 80)
    print(f"[{name}]  (encoding: {encodings[name]})")
    print(f"행 수: {df.shape[0]:,} / 열 수: {df.shape[1]}")
    print(f"중복 행 개수: {df.duplicated().sum():,}")
    print("\n컬럼 정보 (타입, 결측치)")
    display(column_profile(df))
    print("상위 3행")
    display(df.head(3))


for name, df in tables.items():
    describe_table(name, df)

================================================================================
[olist_customers_dataset]  (encoding: utf-8)
행 수: 99,441 / 열 수: 5
중복 행 개수: 0

컬럼 정보 (타입, 결측치)

                          dtype  null_count  null_ratio(%)
customer_id                 str           0            0.0
customer_unique_id          str           0            0.0
customer_zip_code_prefix  int64           0            0.0
customer_city               str           0            0.0
customer_state              str           0            0.0

상위 3행

                        customer_id                customer_unique_id  customer_zip_code_prefix          customer_city customer_state
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0                     14409                 franca             SP
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3                      9790  sao bernardo do campo             SP
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e                      1151              sao paulo             SP

================================================================================
[olist_geolocation_dataset]  (encoding: utf-8)
행 수: 1,000,163 / 열 수: 5

중복 행 개수: 261,831

컬럼 정보 (타입, 결측치)

                               dtype  null_count  null_ratio(%)
geolocation_zip_code_prefix    int64           0            0.0
geolocation_lat              float64           0            0.0
geolocation_lng              float64           0            0.0
geolocation_city                 str           0            0.0
geolocation_state                str           0            0.0

상위 3행

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng geolocation_city geolocation_state
0                         1037       -23.545621       -46.639292        sao paulo                SP
1                         1046       -23.546081       -46.644820        sao paulo                SP
2                         1046       -23.546129       -46.642951        sao paulo                SP

================================================================================
[olist_order_items_dataset]  (encoding: utf-8)
행 수: 112,650 / 열 수: 7
중복 행 개수: 0

컬럼 정보 (타입, 결측치)

                       dtype  null_count  null_ratio(%)
order_id                 str           0            0.0
order_item_id          int64           0            0.0
product_id               str           0            0.0
seller_id                str           0            0.0
shipping_limit_date      str           0            0.0
price                float64           0            0.0
freight_value        float64           0            0.0

상위 3행

                           order_id  order_item_id                        product_id                         seller_id  shipping_limit_date  price  freight_value
0  00010242fe8c5a6d1ba2dd792cb16214              1  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202  2017-09-19 09:45:35   58.9          13.29
1  00018f77f2f0320c557190d7a144bdd3              1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36  2017-05-03 11:05:13  239.9          19.93
2  000229ec398224ef6ca0657da4fc703e              1  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d  2018-01-18 14:48:30  199.0          17.87

================================================================================
[olist_order_payments_dataset]  (encoding: utf-8)
행 수: 103,886 / 열 수: 5
중복 행 개수: 0

컬럼 정보 (타입, 결측치)

                        dtype  null_count  null_ratio(%)
order_id                  str           0            0.0
payment_sequential      int64           0            0.0
payment_type              str           0            0.0
payment_installments    int64           0            0.0
payment_value         float64           0            0.0

상위 3행

                           order_id  payment_sequential payment_type  payment_installments  payment_value
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card                     8          99.33
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card                     1          24.39
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card                     1          65.71

================================================================================
[olist_order_reviews_dataset]  (encoding: utf-8)
행 수: 99,224 / 열 수: 7

중복 행 개수: 0

컬럼 정보 (타입, 결측치)

                         dtype  null_count  null_ratio(%)
review_id                  str           0           0.00
order_id                   str           0           0.00
review_score             int64           0           0.00
review_comment_title       str       87656          88.34
review_comment_message     str       58247          58.70
review_creation_date       str           0           0.00
review_answer_timestamp    str           0           0.00

상위 3행

                          review_id                          order_id  review_score review_comment_title review_comment_message review_creation_date review_answer_timestamp
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb             4                  NaN                    NaN  2018-01-18 00:00:00     2018-01-18 21:46:59
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33             5                  NaN                    NaN  2018-03-10 00:00:00     2018-03-11 03:05:13
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b             5                  NaN                    NaN  2018-02-17 00:00:00     2018-02-18 14:36:24

================================================================================
[olist_orders_dataset]  (encoding: utf-8)
행 수: 99,441 / 열 수: 8

중복 행 개수: 0

컬럼 정보 (타입, 결측치)

                              dtype  null_count  null_ratio(%)
order_id                        str           0           0.00
customer_id                     str           0           0.00
order_status                    str           0           0.00
order_purchase_timestamp        str           0           0.00
order_approved_at               str         160           0.16
order_delivered_carrier_date    str        1783           1.79
order_delivered_customer_date   str        2965           2.98
order_estimated_delivery_date   str           0           0.00

상위 3행

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

================================================================================
[olist_products_dataset]  (encoding: utf-8)
행 수: 32,951 / 열 수: 9
중복 행 개수: 0

컬럼 정보 (타입, 결측치)

                              dtype  null_count  null_ratio(%)
product_id                      str           0           0.00
product_category_name           str         610           1.85
product_name_lenght         float64         610           1.85
product_description_lenght  float64         610           1.85
product_photos_qty          float64         610           1.85
product_weight_g            float64           2           0.01
product_length_cm           float64           2           0.01
product_height_cm           float64           2           0.01
product_width_cm            float64           2           0.01

상위 3행

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

================================================================================
[olist_sellers_dataset]  (encoding: utf-8)
행 수: 3,095 / 열 수: 4
중복 행 개수: 0

컬럼 정보 (타입, 결측치)

                        dtype  null_count  null_ratio(%)
seller_id                 str           0            0.0
seller_zip_code_prefix  int64           0            0.0
seller_city               str           0            0.0
seller_state              str           0            0.0

상위 3행

                          seller_id  seller_zip_code_prefix     seller_city seller_state
0  3442f8959a84dea7ee197c632cb2df15                   13023        campinas           SP
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844      mogi guacu           SP
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031  rio de janeiro           RJ

================================================================================
[product_category_name_translation]  (encoding: utf-8)
행 수: 71 / 열 수: 2
중복 행 개수: 0

컬럼 정보 (타입, 결측치)

                              dtype  null_count  null_ratio(%)
product_category_name           str           0            0.0
product_category_name_english   str           0            0.0

상위 3행

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

## 9개 테이블 요약

In [4]:
summary = pd.DataFrame([
    {
        "table": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "cols_with_nulls": int((df.isna().sum() > 0).sum()),
    }
    for name, df in tables.items()
]).set_index("table")

summary

                                      rows  columns  cols_with_nulls
table
olist_customers_dataset              99441        5                0
olist_geolocation_dataset          1000163        5                0
olist_order_items_dataset           112650        7                0
olist_order_payments_dataset        103886        5                0
olist_order_reviews_dataset          99224        7                2
olist_orders_dataset                 99441        8                3
olist_products_dataset               32951        9                8
olist_sellers_dataset                 3095        4                0
product_category_name_translation       71        2                0